[package]
name = "omv-core"
version = "0.1.0"
authors = ["Wei Tang <wei@that.world>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
anyhow = "1.0.38"
once_cell = "1.4.1"
mirai-annotations = "1.10.1"
ref-cast = "1.0.6"
omv-primitives = { version = "0.1.0", path = "../primitives" }
